Updates to support recent Bazel releases.
Summary:
This change primarily addresses T276, which unblock the use of Bazel versions
more recent than 0.7.0. Unfortunately this required several interlocking
changes that cannot be easily separated. In brief, the changes are:

- Replace our custom protobuf and Go rules with upstream rules.
  We now use "native" aspect-driven proto_library and the Go rules from
  https://github.com/bazelbuild/rules_go.

- Update the version of the protobuf toolchain to 3.5.1.1.
  Add C++ and Java proto toolchains.
  Add bindings for gson and guava required by those external repos.
  Fixes to make the protobuf repo work with zlib.
  (see https://github.com/google/protobuf/issues/2365)

- Update the Go toolchain (allowing Go 1.9, finally).

- Update all our proto_library rules. This will require us to update the tool
  that generates our proto libraries for "go get", but I have not included that
  in this change.

  With this change, per-language generation is handled by separate aspects.
  Add language-specific rules for C++, Go, and Java.

- Disable the Go unit test macros. These will have to be entirely rewritten, as
  the internal plumbing of the upstream rules is new. I'll address that in a
  future change, soon.

These changes now require Bazel ≥ 0.8.0.

The upstream Go rules broke many of our tests that were based on the sh_test
rule.  To address this, add a shell_tool_test macro that simplifies the
plumbing needed to pass tool paths in to the shell tests, without having to
entirely rewrite them.  All our sh_test rules that depended on Go binaries are
now updated.

Test Plan:
  bazel clean ; for op in build test ; do bazel $op kythe/... ; done
  bazel build $(bazel query kythe/docs/...)

Reviewers: zarko, #core_team, schroederc

Reviewed By: zarko, #core_team, schroederc

Subscribers: shahms, schroederc, salguarnieri, zarko, #core_team

Differential Revision: https://phabricator-dot-kythe-repo.appspot.com/D2122

diff --git a/kythe/go/platform/tools/kindex_file_generator/BUILD b/kythe/go/platform/tools/kindex_file_generator/BUILD
--- a/kythe/go/platform/tools/kindex_file_generator/BUILD
+++ b/kythe/go/platform/tools/kindex_file_generator/BUILD
@@ -1,4 +1,5 @@
 load("@io_bazel_rules_go//go:def.bzl", "go_binary")
+load("//tools:build_rules/testing.bzl", "shell_tool_test")
 
 package(default_visibility = ["//kythe:default_visibility"])
 
@@ -8,20 +9,39 @@ go_binary(
     deps = [
         "//kythe/go/platform/kindex",
         "//kythe/go/util/kytheuri",
-        "//kythe/proto:storage_proto_go",
+        "//kythe/proto:storage_go_proto",
         "@go_protobuf//:proto",
     ],
 )
 
-sh_test(
+shell_tool_test(
     name = "kindex_file_generator_test",
-    size = "small",
-    srcs = [
-        "kindex_file_generator_test.sh",
-    ],
-    data = [
-        ":kindex_file_generator",
-        "//kythe/cxx/tools:kindex_tool",
-        "//kythe/testdata:BUILD",
-    ],
+    script = ["""
+    tmp="$$(mktemp -d 2>/dev/null || mktemp -d -t kythetest)"
+    trap 'rm -rf "$$tmp"' EXIT ERR INT
+
+    kindex_output="$$tmp/temp.kindex"
+    $$generator \\
+      --uri "kythe://kythe?lang=bazel?path=kythe/BUILD#//kythe/BUILD" \\
+      --output "$$kindex_output" \\
+      --source "$$input"
+
+    size="$$(du -k "$$kindex_output" | cut -f1)"
+    if [[ "$$size" -eq 0 ]] ; then
+       echo "FAILED: output $$kindex_output is empty"
+       exit 1
+    fi
+
+    $$kindex -explode "$$kindex_output"
+
+    if [[ ! -e "$${kindex_output}_UNIT" ]] ; then
+      echo "FAILED: Exploded kindex UNIT file not found"
+      exit 1
+    fi
+    """],
+    tools = {
+        "generator": ":kindex_file_generator",
+        "kindex": "//kythe/cxx/tools:kindex_tool",
+        "input": "//kythe/testdata:BUILD",
+    },
 )
